#!/bin/sh
touch tmp/restart.txt
echo "restarting All Your Photos after receiving push"

export NODE_ENV=production 
export PORT=3000


npm install
npm test
mason build .

pkill -f 'foreman start'
foreman start >> /var/log/allyourphotos/foreman.log