#!/bin/sh
touch tmp/restart.txt
echo "restarting All Your Photos after receiving push"

# provisioning 
#sudo gem install mason 
#sudo gem install foreman 
#sudo npm install -g foreman
#sudo nf export -a app -o /etc/init
#sudo npm install -g grunt-cli

export MONGOHQ_URL=mongodb://R:billion@ec2-54-228-162-49.eu-west-1.compute.amazonaws.com/allyourphotos
export NODE_ENV=production

npm install
#npm test
#mason build app

#sudo stop app
#sudo pkill "node"

sudo bower install
sudo grunt build
sudo restart app
sudo chmod 700 deploy/monit
sudo chown root deploy/monit
sudo monit -d 60 -c deploy/monit
sudo service nginx restart # clear cache
#foreman start web=1
