#!/bin/sh
touch tmp/restart.txt
echo "restarting All Your Photos after receiving push"

export NODE_ENV=production 
export PORT=3000


npm install
npm test
mason build .

sudo stop app
pkill -f "node"

sudo foreman export upstart /etc/init -p 3000 -u ec2-user
sudo start app
