#!/usr/bin/env bash
set -e
oldrev=$1
newrev=$2

run() {
  [ -x $1 ] && $1 $oldrev $newrev
}

echo files changed: $(git diff $oldrev $newrev --diff-filter=ACDMR --name-only | wc -l)

umask 002

# add these to your provisioning file
# sudo npm install foreman -g
# sudo gem install mason
# 
# for ssl support:
# sudo setcap 'cap_net_bind_service=+ep' /usr/local/bin/node
# OR:
# sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443
# sudo iptables -t nat -A OUTPUT -p tcp --dport 443 -o lo -j REDIRECT --to-port 8443

# sudo foreman export --app ayp upstart /etc/init

git submodule init && git submodule sync && git submodule update

# do we have all we need?
mason build
mason buildpacks:install https://github.com/heroku/heroku-buildpack-nodejs.git

run deploy/before_restart
run deploy/restart && run deploy/after_restart
